question_data = [
         {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "hard",
          "question": "The retail disc of Tony Hawk&#039;s Pro Skater 5 only comes with the tutorial.",
          "correct_answer": "True", "incorrect_answers": ["False"]},
         {"category": "Vehicles", "type": "boolean", "difficulty": "hard",
          "question": "In 1993 Swedish car manufacturer Saab experimented with replacing the steering wheel with a joystick in a Saab 9000.",
          "correct_answer": "True", "incorrect_answers": ["False"]},
         {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "hard",
          "question": "In &quot;The Sims&quot; series, the most members in a household you can have is 8.",
          "correct_answer": "True", "incorrect_answers": ["False"]},
         {"category": "History", "type": "boolean", "difficulty": "hard",
          "question": "Japan was part of the Allied Powers during World War I.", "correct_answer": "True",
          "incorrect_answers": ["False"]},
         {"category": "History", "type": "boolean", "difficulty": "hard",
          "question": "The Kingdom of Prussia briefly held land in Estonia.",
          "correct_answer": "False", "incorrect_answers": ["True"]},
         {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "hard",
          "question": "Unturned originally started as a Roblox game.", "correct_answer": "True",
          "incorrect_answers": ["False"]},
         {"category": "History", "type": "boolean", "difficulty": "hard",
          "question": "Joseph Stalin&#039;s real name was Ioseb Bessarionis dze Dzugashvili.",
          "correct_answer": "True", "incorrect_answers": ["False"]},
         {"category": "Entertainment: Comics", "type": "boolean", "difficulty": "hard",
          "question": "In the comic book &quot;Archie&quot;, Betty is friends with Veronica because she is rich.",
          "correct_answer": "False", "incorrect_answers": ["True"]},
         {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "hard",
          "question": "In the game &quot;Melty Blood Actress Again Current Code&quot;, you can enter Blood Heat mode in Half Moon style.",
          "correct_answer": "False", "incorrect_answers": ["True"]},
         {"category": "Science & Nature", "type": "boolean", "difficulty": "hard",
          "question": "It was once believed that injecting shark cartilage into people would prevent them from contracting cancer.",
          "correct_answer": "True", "incorrect_answers": ["False"]},
         {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "hard",
          "question": "The first &quot;Metal Gear&quot; game was released for the PlayStation 1.",
          "correct_answer": "False",
          "incorrect_answers": ["True"]},
         {"category": "Science: Mathematics", "type": "boolean", "difficulty": "hard",
          "question": "The binary number &quot;101001101&quot; is equivalent to the Decimal number &quot;334&quot;",
          "correct_answer": "False", "incorrect_answers": ["True"]},
         {"category": "General Knowledge", "type": "boolean", "difficulty": "hard",
          "question": "&quot;Number 16 Bus Shelter&quot; was a child&#039;s name that was approved by the New Zealand government.",
          "correct_answer": "True", "incorrect_answers": ["False"]},
         {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "hard",
          "question": "TF2: Sentry rocket damage falloff is calculated based on the distance between the sentry and the enemy, not the engineer and the enemy",
          "correct_answer": "False", "incorrect_answers": ["True"]},
         {"category": "Mythology", "type": "boolean", "difficulty": "hard",
          "question": "Rannamaari was a sea demon that haunted the people of the Maldives and had to be appeased monthly with the sacrifice of a virgin girl.",
          "correct_answer": "True", "incorrect_answers": ["False"]},
         {"category": "Entertainment: Japanese Anime & Manga", "type": "boolean", "difficulty": "hard",
          "question": "Throughout the entirety of &quot;Dragon Ball Z&quot;, Goku only kills two characters: a miniboss named Yakon and Kid Buu.",
          "correct_answer": "True", "incorrect_answers": ["False"]},
         {"category": "Entertainment: Music", "type": "boolean", "difficulty": "hard",
          "question": "The song &quot;Mystery Train&quot; was released by artist &quot;Little Junior&#039;s Blue Flames&quot; in 1953.",
          "correct_answer": "True", "incorrect_answers": ["False"]},
         {"category": "Science: Computers", "type": "boolean", "difficulty": "hard",
          "question": "The IBM PC used an Intel 8008 microprocessor clocked at 4.77 MHz and 8 kilobytes of memory.",
          "correct_answer": "False", "incorrect_answers": ["True"]},
         {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "hard",
          "question": "The names of Roxas&#039;s Keyblades in Kingdom Hearts are &quot;Oathkeeper&quot; and &quot;Oblivion&quot;.",
          "correct_answer": "True", "incorrect_answers": ["False"]},
         {"category": "Geography", "type": "boolean", "difficulty": "hard",
          "question": "Switzerland has four national languages, English being one of them.", "correct_answer": "False",
          "incorrect_answers": ["True"]},
         {"category": "Politics", "type": "boolean", "difficulty": "hard",
          "question": "Joko Widodo has appeared in the cover of a TIME magazine.",
          "correct_answer": "True", "incorrect_answers": ["False"]},
         {"category": "Entertainment: Music", "type": "boolean", "difficulty": "hard",
          "question": "The band STRFKR was also briefly known as Pyramiddd.", "correct_answer": "True",
          "incorrect_answers": ["False"]},
         {"category": "History", "type": "boolean", "difficulty": "hard",
          "question": "The USS Missouri (BB-63) last served in the Korean War.",
          "correct_answer": "False", "incorrect_answers": ["True"]},
         {"category": "Entertainment: Japanese Anime & Manga", "type": "boolean", "difficulty": "hard",
          "question": "Druid is a mage class in &quot;Log Horizon&quot;.", "correct_answer": "False",
          "incorrect_answers": ["True"]},
         {"category": "Entertainment: Television", "type": "boolean", "difficulty": "hard",
          "question": "The Klingon home planet is Q'onoS.", "correct_answer": "True",
          "incorrect_answers": ["False"]},
         {"category": "Entertainment: Board Games", "type": "boolean", "difficulty": "hard",
          "question": "The board game Go has more possible legal positions than the number of atoms in the visible universe.",
          "correct_answer": "True", "incorrect_answers": ["False"]},
         {"category": "Celebrities", "type": "boolean", "difficulty": "hard",
          "question": "Lady Gaga&#039;s real name is Stefani Joanne Angelina Germanotta.", "correct_answer": "True",
          "incorrect_answers": ["False"]},
         {"category": "Science: Mathematics", "type": "boolean", "difficulty": "hard",
          "question": "In Topology, the complement of an open set is a closed set.",
          "correct_answer": "True", "incorrect_answers": ["False"]},
         {"category": "Science & Nature", "type": "boolean", "difficulty": "hard",
          "question": "The value of one Calorie is different than the value of one calorie.", "correct_answer": "True",
          "incorrect_answers": ["False"]},
         {"category": "History", "type": "boolean", "difficulty": "hard",
          "question": "During the Winter War, the amount of Soviet Union soliders that died or went missing was five times more than Finland&#039;s.",
          "correct_answer": "True", "incorrect_answers": ["False"]},
         {"category": "General Knowledge", "type": "boolean", "difficulty": "hard",
          "question": "Stagecoach owned &quot;South West Trains&quot; before losing the rights to FirstGroup and MTR in March of 2017.",
          "correct_answer": "True", "incorrect_answers": ["False"]},
         {"category": "Entertainment: Film", "type": "boolean", "difficulty": "hard",
          "question": "The weapon Clint Eastwood uses in &quot;Dirty Harry&quot; was a .44 Automag.",
          "correct_answer": "False", "incorrect_answers": ["True"]},
         {"category": "Science: Mathematics", "type": "boolean", "difficulty": "hard",
          "question": "L&#039;H&ocirc;pital was the mathematician who created the homonymous rule that uses derivatives to evaluate limits with indeterminations.",
          "correct_answer": "False", "incorrect_answers": ["True"]},
         {"category": "Politics", "type": "boolean", "difficulty": "hard",
          "question": "George Clinton, Vice President of the United States (1805-1812), is an ancestor of President Bill Clinton.",
          "correct_answer": "False", "incorrect_answers": ["True"]},
         {"category": "Entertainment: Music", "type": "boolean", "difficulty": "hard",
          "question": "Pete Townshend&#039;s solo album, &quot;White City: A Novel&quot;, is set in the metropolitan area of Chicago.",
          "correct_answer": "False", "incorrect_answers": ["True"]},
         {"category": "Entertainment: Japanese Anime & Manga", "type": "boolean", "difficulty": "hard",
          "question": "In the &quot;To Love-Ru&quot; series, Peke is considered a female robot.",
          "correct_answer": "True",
          "incorrect_answers": ["False"]},
         {"category": "General Knowledge", "type": "boolean", "difficulty": "hard",
          "question": "Spoon theory is a theory, utilizing &quot;Spoons&quot; as a metaphor for energy they can use in a day.",
          "correct_answer": "True", "incorrect_answers": ["False"]},
         {"category": "Entertainment: Music", "type": "boolean", "difficulty": "hard",
          "question": "The song Scatman&#039;s World was released after Scatman (Ski-Ba-Bop-Ba-Dop-Bop).",
          "correct_answer": "True", "incorrect_answers": ["False"]},
         {"category": "Entertainment: Japanese Anime & Manga", "type": "boolean", "difficulty": "hard",
          "question": "In the &quot;Kagerou Daze&quot; series, Shintaro Kisaragi is prominently shown with the color red.",
          "correct_answer": "True", "incorrect_answers": ["False"]},
         {"category": "Mythology", "type": "boolean", "difficulty": "hard",
          "question": "Janus was the Roman god of doorways and passageways.", "correct_answer": "True",
          "incorrect_answers": ["False"]},
         {"category": "Entertainment: Music", "type": "boolean", "difficulty": "hard",
          "question": "The singer Billie Holiday was also known as &quot;Lady Day&quot;.",
          "correct_answer": "True", "incorrect_answers": ["False"]},
         {"category": "Entertainment: Japanese Anime & Manga", "type": "boolean", "difficulty": "hard",
          "question": "The character Plum from &quot;No Game No Life&quot; is a girl.", "correct_answer": "False",
          "incorrect_answers": ["True"]},
         {"category": "Vehicles", "type": "boolean", "difficulty": "hard",
          "question": "The term 'GTO' was originated by Ferrari?",
          "correct_answer": "True", "incorrect_answers": ["False"]},
         {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "hard",
          "question": "In &quot;Minecraft&quot;, gold tools are faster than diamond tools.", "correct_answer": "True",
          "incorrect_answers": ["False"]},
         {"category": "Art", "type": "boolean", "difficulty": "hard",
          "question": "The Statue of Liberty's official name is 'Liberty Enlightening the World'.",
          "correct_answer": "True", "incorrect_answers": ["False"]},
         {"category": "History", "type": "boolean", "difficulty": "hard",
          "question": "The man that shot Alexander Hamilton was named Aaron Burr.", "correct_answer": "True",
          "incorrect_answers": ["False"]},
         {"category": "Entertainment: Film", "type": "boolean", "difficulty": "hard",
          "question": "YouTube personality Jenna Marbles served as an executive producer of the film Maximum Ride (2016).",
          "correct_answer": "True", "incorrect_answers": ["False"]},
         {"category": "Science: Computers", "type": "boolean", "difficulty": "hard",
          "question": "The T-Mobile Sidekick smartphone is a re-branded version of the Danger Hiptop.",
          "correct_answer": "True", "incorrect_answers": ["False"]},
         {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "hard",
          "question": "The Paradox Interactive game Stellaris was released in 2016.",
          "correct_answer": "True",
          "incorrect_answers": ["False"]},
         {"category": "Entertainment: Video Games",
          "type": "boolean",
          "difficulty": "hard",
          "question": "In The Witcher 3, the Zoltan Chivay Gwent card can be found under the Hanged Man&#039;s Tree.",
          "correct_answer": "True",
          "incorrect_answers": ["False"]}]
